import Head from 'next/head'
import About from '../components/About'
import Main from '../components/Main'
import Navbar from '../components/Navbar'
import { Projects } from '../components/Projects'
import Skills from '../components/Skills'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Juesgape</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/main-icon.png" />
      </Head>

    <Navbar></Navbar>
    <Main></Main>
    <About></About>
    <Skills></Skills>
    <Projects></Projects>

    </div>
  )
}
